POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "fullname" : "Le Bon",
    "email" : "lebon@gmail.com",
    "password" : "789456"
}
###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "fullname" : "koribeche amir",
    "email" : "amir@gmail.com",
    "password" : "123456"
}

###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "fullname" : "Le bien",
    "email" : "lebien@gmail.com",
    "password" : "741963"
}
###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email" : "amir@gmail.com",
    "password" : "123456"
}

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email" : "lebien@gmail.com",
    "password" : "741963"
}

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email" : "lebon@gmail.com",
    "password" : "789456"
}

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email" : "lebien@gmail.com",
    "password" : "741963"
}

###-------------Inserer une nouvelle annonce "casquette"
GET http://localhost:5000/api/annonce
Content-Type: application/json

{
    "nom": "casquette",
    "prix": 200,
    "description": "La description",
    "photo": "la photo",
    "qteDispo": 2
}

###-------------Inserer une nouvelle annonce "veste"-----------//
// On ajoute une authorisation ( bearer + token de connexion utilisateur )  
POST http://localhost:5000/api/annonce
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYThlNDBjNDFjOGEyNDBiOWM0Njg4YyIsImlhdCI6MTY1NTIzNTgyNX0.HzDrAd9kmIx-Z4yJ8fR4FLtjyxBbnPZVk5JxWIKNqW4
{
    "nom": "veste",
    "prix": 150,
    "description": "La veste autonne",
    "photo": "la photo",
    "qteDispo": 3
}
###------------Mettre à jour une annonce-----------------------// 
// On ajoute une authorisation ( bearer + token de connexion utilisateur ) 
PUT http://localhost:5000/api/annonce
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYThlNDBjNDFjOGEyNDBiOWM0Njg4YyIsImlhdCI6MTY1NTIzNTgyNX0.HzDrAd9kmIx-Z4yJ8fR4FLtjyxBbnPZVk5JxWIKNqW4
{
    "nom": "veste",
    "prix": 155,
    "description": "La veste autonne neuve",
    "photo": "la photo",
    "qteDispo": 3
}

###-----------Supprimer une annonce-----------------------// 
// On ajoute une authorisation ( bearer + token de connexion utilisateur ) 
DELETE  http://localhost:5000/api/annonce
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYThlNDBjNDFjOGEyNDBiOWM0Njg4YyIsImlhdCI6MTY1NTIzNTgyNX0.HzDrAd9kmIx-Z4yJ8fR4FLtjyxBbnPZVk5JxWIKNqW4
{
    "nom": "veste",
    "prix": 155,
    "description": "La veste autonne neuve",
    "photo": "la photo",
    "qteDispo": 3
}